### ISSUE TITLE
How to use placeholder

### ISSUE THREAD

**Issue by JcmeLs** [amitshekhariitbhu/AndroidTensorFlowMachineLearningExample#2]
I want to use tensorflow model in android.But I don't know how to use placeholder.Can you help me?

**Comment by amitshekhariitbhu** [comment]
Please refer this [link](http://learningtensorflow.com/lesson4/)

**Comment by JcmeLs** [comment]
@amitshekhariitbhu Thanks,but,I know how to use placeholder in python.But in java,I don't know how to use it.

**Comment by amitshekhariitbhu** [comment]
@JcmeLs ok I will check few reference and tell u

**Comment by JcmeLs** [comment]
@amitshekhariitbhu Thank you very much!Looking forward to your reply！Thanks again!

**Comment by JcmeLs** [comment]
Hi~I did not find argmax in official documents.Do you have any suggestions?

**Comment by JcmeLs** [comment]
I used C++ API to run my model.So close.
